name: Release

on:
  push:
    branches: [prod, staging]

env:
  CURRENT_SERVICE: utxo-global-multi-sig-website
  PROJECT_ID: fewcha-450202
  REGION: us-central1
  GKE_CLUSTER: fewcha-gke

jobs:
  build_and_publish:
    name: Build And Publish
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4

      - name: Extract NAMESPACE from ref_name
        id: extract_namespace
        run: |
          NAMESPACE="${GITHUB_REF_NAME##*/}"
          echo "NAMESPACE=$NAMESPACE" >> "$GITHUB_ENV"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        id: auth
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: "projects/624428081092/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "github-actions-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Get GKE credential
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Service docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.CURRENT_SERVICE }}/${{ env.CURRENT_SERVICE }}:${{ env.NAMESPACE }}
          cache-from: type=registry,ref=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.CURRENT_SERVICE }}/${{ env.CURRENT_SERVICE }}:${{ env.NAMESPACE }}
          cache-to: type=inline
          build-args: BUILD_ENV=${{ github.ref_name }}

      - name: Apply to K8S
        run: |-
          kubectl rollout restart -n utxo-global-${{ env.NAMESPACE }} deploy ${{ env.CURRENT_SERVICE }}
